### ISSUE TITLE
一些文档中的错别字

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/awesome-DeepLearning#102]
### 1. 错别字

登场 &rarr; 等长

![image](https://user-images.githubusercontent.com/9301846/122001065-55293900-cde2-11eb-956d-e15114d5968c.png)

由 &rarr; 有
https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/model_tuning/attention/classic_attention.html
![image](https://user-images.githubusercontent.com/9301846/122010816-0da8aa00-cdee-11eb-80e4-ffc21a792186.png)

### 2. 格式错误
https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/metrics/GAN%20Evaluation.html

![image](https://user-images.githubusercontent.com/9301846/122002589-860a6d80-cde4-11eb-997b-3b03f2ef7464.png)

https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/optimizers/gd.html

![image](https://user-images.githubusercontent.com/9301846/122003555-d209e200-cde5-11eb-84c5-46db4e7a0859.png)

https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/loss_functions/CE_Loss.html

![image](https://user-images.githubusercontent.com/9301846/122008225-5dd23d00-cdeb-11eb-95de-af1abbeed510.png)

### 3. 链接跳转
https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/model_tuning/normalization/basic_normalization.html

![image](https://user-images.githubusercontent.com/9301846/122009591-d08fe800-cdec-11eb-9e28-d0aecbf538be.png)

### 4. 图片显示问题
https://paddlepedia.readthedocs.io/en/latest/tutorials/deep_learning/model_tuning/normalization/basic_normalization.html
![image](https://user-images.githubusercontent.com/9301846/122009737-f4532e00-cdec-11eb-8c08-5c6f937f9915.png)

![image](https://user-images.githubusercontent.com/9301846/122010010-42683180-cded-11eb-8223-ad7f6affcc94.png)

https://paddlepedia.readthedocs.io/en/latest/tutorials/CNN/convolution_operator/Convolution.html
![image](https://user-images.githubusercontent.com/9301846/122016022-3aab8b80-cdf3-11eb-9029-3ad4b2642229.png)

**Comment by chajchaj** [comment]
谢谢反馈，我们会尽快修复。
同时，我们欢迎各界开发者提PR，一起建设awesome-DeepLearning。

**Comment by w5688414** [comment]
随机梯度下降公式显示问题pr, https://github.com/PaddlePaddle/awesome-DeepLearning/pull/105
