### ISSUE TITLE
深度学习百问里面部分无图

### ISSUE THREAD

**Issue by yuzhi535** [PaddlePaddle/awesome-DeepLearning#575]
https://paddlepedia.readthedocs.io/en/latest/tutorials/CNN/convolution_operator/Dilated_Convolution.html
此链接里面没有图4
![Screenshot_20210726_105416](https://user-images.githubusercontent.com/57068558/126926809-81b2bea8-93a1-49b5-98cd-d6ab5507591e.png)

**Comment by lvjian0706** [comment]
您好，非常感谢您的反馈，此问题已经修改。
